service: fe1-slackbot
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  profile: default
  region: ap-northeast-2

  runtime: nodejs20.x
  stage: prod # 기본 stage를 "prod"로 설정
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    ATLASSIAN_TOKEN: ${env:ATLASSIAN_TOKEN}
    GROQ_API_KEY: ${env:GROQ_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - arn:aws:lambda:ap-northeast-2:*:function:fe1-slackbot-prod-slack

functions:
  slack:
    handler: app.handler
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: slack/events
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3086

package:
  include:
    - app.js
  exclude:
    - node_modules/**
    - src/**
    - ./**
